### ISSUE TITLE
Account is logged out, issue

### ISSUE THREAD

**Issue by NiR0Lf** [tducasse/go-instabot#29]
![image](https://user-images.githubusercontent.com/44731168/47955089-0876f380-df93-11e8-8a96-d275bd1d3f77.png)

**Comment by tducasse** [comment]
Hi,
You have to give me some context here, a screenshot is not very self explanatory.
What did you do to get this error exactly?
If you have been using multiple accounts, that might be a problem, Instagram may have banned this account.
Try to login through the web interface to see if your account is working.
Otherwise, try to remove the `session` and `key` files and try again.
