### ISSUE TITLE
ERROR:The account is logged out

### ISSUE THREAD

**Issue by momododo** [tducasse/go-instabot#47]
everytime that in run the bot
its say
ERROR:The account is logged out
then i go to my instagram and i need to CONFIRM  that it was me and then i just try to use the bot again and its saying the same error
and repeat

**Comment by basti3893** [comment]
have you found a solution?

**Comment by kopaygorodsky** [comment]
it's a possible bug from goinsta lib that used in this project. I suppose they generate some device id randomly and when you click 'It was me' it accepts it, but next time you run the app - it generates a new one :) endless loop

**Comment by claudiobosetti** [comment]
Disable 2FA, it will work.

**Comment by PierreBlanchet** [comment]
> Disable 2FA, it will work.

Hi,

I did i too but I still have the same error whatever I'm trying.
Do you have an idea @tducasse ? :)

**Comment by PierreBlanchet** [comment]
> > Disable 2FA, it will work.
> 
> Hi,
> 
> I did i too but I still have the same error whatever I'm trying.
> Do you have an idea @tducasse ? :)

I tried to look at the code and study a bit the behavior of it and here is what I found. When I run the command to launch it appears that instagram is just denying the request because they don't know the virtual device used. Then when I go on instagram they asked me if it was really me. I answer Yes but it doesn't change anything because I guess the code use a random identifier each time which makes instagram see each connection tentative as different. Therefore the way to solve this issue would be to use the same identifier twice, once for accepting the request on instagram and once to launch the code.

Does anyone know which part of the code I can modify for that ? (It's more in the goinsta repo I think). I'm looking too and will keep you updated if I find something.
