### ISSUE TITLE
-bash: Retrying after error: fail: login_required

### ISSUE THREAD

**Issue by Hawksama** [tducasse/go-instabot#65]
Hi tducasse,

After using the bot for a few hours, suddenly an error occurred:
`2020/10/09 21:26:23 ERROR:: challenge_required`

and then 

```
~/go/src/github.com/tducasse/go-instabot$ go-instabot -run
2020/10/09 21:46:12 Using config: config/config.json

2020/10/09 21:46:12 Successfully logged in
2020/10/09 21:46:12 Fetching the list of images for #christening

2020/10/09 21:46:32 Retrying after error: fail: login_required ()
```

Is there a problem with how I use the bot? The JSON config is correct.

**Comment by tducasse** [comment]
`challenge required` means that you need to enter a captcha directly in your instagram account. Basically go back to your instagram account and login again, with your phone or desktop computer, and it should be okay. Using the bot too much is probably be interpreted as spam from instagram, and that's why you get this.

**Comment by Hawksama** [comment]
Hmm.. thank you for this fast reply but I've logged in from the web, the app and also changed the password without any luck.

**Comment by tducasse** [comment]
Sorry then I don't know!

**Comment by Hawksama** [comment]
Would you help if I share with you any logs?

**Comment by Hawksama** [comment]
Well, I solved it. I've reverse-engineered your application and saw that there was a problem with the saved session. Deleting the goinsta-session and rebuilding the session with the new information, worked.
